image: continuumio/anaconda3:2019.03
stages:
  - check-files
  - lint
  - run

check-lab3-files:
  tags:
    - docker
  stage: check-files
  script:
    - test -f .gitignore
    - test -f .pylintrc
    - test -f common/test_env.py
    - test -f main.py
    - find . -name "*" -not -path "./.git/*" -not -path "./builds/*" 2>&1

lint-lab3:
  tags:
    - docker
  stage: lint
  script:
    # Check formatting
    - conda install -c conda-forge autopep8
    - autopep8 -d --exit-code main.py
    # Lint
    - pylint main.py

run-lab3:
  tags:
    - docker
  stage: run
  script:
    - chmod +x main.py
    - ./main.py
  artifacts:
    name: lab3-results-$CI_COMMIT_SHORT_SHA
    paths:
      - results/
